# Config file for automatic testing at travis-ci.org
language: python

python: 2.7

env:
  global:
    - secure: "Afb37pdtzDLzNhr/a7Q3VkEzEVYXBRdEq6Y9redmRyZLDrh5o0D92XdSfEMJ9EUuu+n/rLrPTXWlMONtBkejIBFWnyQIStJ0um7iRp3PWlLMUso4XJjPnq9R2WHors2Y7ZDArdfNKxz2LV3CfnxdIYLziGf/P1TiQX24B3INdYc="
  matrix:
    - TOX_ENV=py34
    - TOX_ENV=py33
    - TOX_ENV=py27
    - TOX_ENV=pypy

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
